formatter: "markdown table"

header-from: "docs/header.md"

content: |-
  {{ .Header }}
  ## Example
  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
output:
  mode: inject
